# tf-runner.yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
# kind: Terraform
kind: Tofu
metadata:
  name: proxmox-vm-provisioner  # ロック問題を回避するためv3に変更
  namespace: flux-system
spec:
  approvePlan: "auto"
  interval: 1m
  path: ./terraform/proxmox-vms
  sourceRef:
    kind: GitRepository
    name: terraform-resources
    namespace: flux-system
  serviceAccountName: tf-runner
  runnerPodTemplate:
    spec:
      image: ghcr.io/flux-iac/tf-runner:v0.16.0-rc.8
      env: 
        - name: PROXMOX_VE_ENDPOINT
          value: /mnt/secrets/proxmox/endpoint
        - name: PROXMOX_VE_API_TOKEN
          value: /mnt/secrets/proxmox/api_token
        - name: GITHUB_TOKEN
          value: /mnt/secrets/github/token
      volumeMounts:
        - name: github-secrets
          mountPath: /mnt/secrets/github
          readOnly: true
        - name: proxmox-secrets
          mountPath: /mnt/secrets/proxmox
          readOnly: true
      volumes:
        - name: github-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: github-vault-secrets
        - name: proxmox-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: proxmox-vault-secrets