# tf-runner.yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: proxmox-vm-provisioner  # ロック問題を回避するためv3に変更
  namespace: flux-system
spec:
  approvePlan: "auto"
  interval: 1m
  path: ./terraform/proxmox-vms
  sourceRef:
    kind: GitRepository
    name: terraform-resources
    namespace: flux-system
  serviceAccountName: tf-runner
  runnerPodTemplate:
    spec:
      image: ghcr.io/flux-iac/tf-runner:v0.16.0-rc.8
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "1Gi"
      
      volumes:
        - name: github-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: github-auth
        - name: proxmox-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: proxmox-auth

      volumeMounts:
        - name: github-secrets
          mountPath: /mnt/secrets/github
          readOnly: true
        - name: proxmox-secrets
          mountPath: /mnt/secrets/proxmox
          readOnly: true

      env:
        - name: TF_VAR_github_token
          valueFrom:
            secretKeyRef:
              name: github-vault-secrets
              key: github_token

        - name: TF_VAR_api_token
          valueFrom:
            secretKeyRef:
              name: proxmox-auth
              key: api_token

        - name: TF_VAR_username
          valueFrom:
            secretKeyRef:
              name: proxmox-auth
              key: username

        - name: TF_VAR_password
          valueFrom:
            secretKeyRef:
              name: proxmox-auth
              key: password